site_name: Spider
site_description: 'A small dart library to generate Assets dart code from assets folder.'
site_author: 'Birju Vachhani'
site_url: 'https://birjuvachhani.github.io/spider/'
remote_branch: gh-pages

# docs_dir: docs-gen

repo_name: 'spider'
repo_url: 'https://github.com/birjuvachhani/spider'

theme:
  name: 'material'
  language: 'en'
  palette:
    scheme: default
    primary: black
    accent: teal
    
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/birjuvachhani
    - icon: fontawesome/brands/medium
      link: https://medium.com/birjuvachhani
    - icon: fontawesome/brands/github
      link: https://github.com/birjuvachhani