// Copyright © 2020 Birju Vachhani. All rights reserved.
// Use of this source code is governed by an Apache license that can be
// found in the LICENSE file.

/// A template for `yaml` config file generation.
const String YAML_CONFIG_TEMPLATE = '''# Generated by Spider

# Generates unit tests to verify that the assets exists in assets directory
generate_tests: true

# Use this to remove vcs noise created by the `generated` comments in dart code
no_comments: true

# Exports all the generated file as the one library
export: true

# This allows you to import all the generated references with 1 single import!
use_part_of: true

# Generates a variable that contains a list of all asset values.
use_references_list: false

# Generates dart font family references for fonts specified in pubspec.yaml
# fonts: true

# Location where all the generated references will be stored
package: resources

groups:
  - class_name: Images
    path: assets/images
    types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
#  - path: assets/vectors
#    class_name: Svgs
#    package: res
#    types: [ .svg ]''';

/// A template for config creation inside pubspec.yaml file.
const String YAML_PUBSPEC_CONFIG_TEMPLATE = '''
# Generated by Spider
spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false
  # Location where all the generated references will be stored
  package: resources
  groups:
    - path: assets/images
      class_name: Images
      types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]''';
