/*
 * Copyright © 2020 Birju Vachhani
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const String YAML_CONFIGS = '''# Generated by Spider

generate_tests: true

groups:
  - path: assets/images
    class_name: Images
    package: res
    types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
#  - path: assets/vectors
#    class_name: Svgs
#    package: res
#    types: [ .svg ]






# MANUAL:

# ===========================================================================================
# KEY               TYPE                DESCRIPTION                             REQUIRED?
# ===========================================================================================
# path/paths        [STRING]            Where to locate assets?                 [REQUIRED]
# -------------------------------------------------------------------------------------------
# class_name        [STRING]            What will be the name of                [REQUIRED]
#                                       generated dart class?
# -------------------------------------------------------------------------------------------
# package           [STRING]            Where to generate dart code             [OPTIONAL]
#                                       in the lib folder?
# -------------------------------------------------------------------------------------------
# file_name         [STRING]            What will be the name of the            [OPTIONAL]
#                                       generated dart file?
# -------------------------------------------------------------------------------------------
# prefix            [STRING]            What will be the prefix of              [OPTIONAL]
#                                       generated dart references?
# -------------------------------------------------------------------------------------------
# types             [LIST<STRING>]      Which types of assets should            [OPTIONAL]
#                                       be included?
# -------------------------------------------------------------------------------------------
# generate_test     [LIST<STRING>]      generate test cases to make sure        [OPTIONAL]
#                                       that asssets are still present in
#                                       the project?
# ===========================================================================================
''';
