name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
      - name: Build & Install Locally
        run: pub global activate --source path .
      - name: Format code
        run: dart format --fix .
      - name: Build Runner
        run: pub run build_runner build --delete-conflicting-outputs
      - name: Check Publish Warnings
        run: pub publish --dry-run
      - name: Publish Package
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: false
